version: '3.8'

services:
  airflow:
    image: apache/airflow:2.6.3-python3.10
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=$(python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: "airflow webserver"
    entrypoint: /bin/bash -c 'airflow db init && exec airflow webserver'
  
  airflow-init:
    image: apache/airflow:2.6.3-python3.10
    entrypoint: /bin/bash
    command: "airflow db init"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

volumes:
  airflow_db: {}